FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
WORKDIR /app

COPY . ./
RUN dotnet restore 'api/netcore-api.csproj'

RUN dotnet publish 'api/netcore-api.csproj' -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime
WORKDIR /app

COPY --from=build-env /app/out .
#ENTRYPOINT ["dotnet", "GigaSecurity.Api.dll"]
